---
- name: Install dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - nginx

- name: Add NGINX configuration
  template: src={{ item.template }}.nginx.j2 dest=/etc/nginx/sites-available/{{ item.fqdn }}
  with_items: "{{ websites }}"
  notify:
    - reload nginx

- name: Enable NGINX configuration
  file: path=/etc/nginx/sites-enabled/{{ item.fqdn }} src=/etc/nginx/sites-available/{{ item.fqdn }} state=link
  with_items: "{{ websites }}"
  notify:
    - reload nginx

- name: Allow HTTP connections
  ufw: rule=allow port=80 proto=tcp

- name: Allow HTTPS connections
  ufw: rule=allow port=443 proto=tcp
