---
user: ordsys
process_group: www-data
fqdn: "ordsys.utn.se"
install_root: /var/www
project_name: ordsys
project_folder: "{{ install_root }}/{{ project_name }}"
project_repo: "git@github.com:chwallen/ordsys.git"
node_version: "14.8.0"
db_name: ordsys
db_user: ordsys
db_password: "{{ vault_ordsys_db_password }}"
django_secret_key: "{{ vault_ordsys_secret_key }}"
django_settings: ordsys.settings.production
pythonpath: "{{ project_folder }}/ordsys"
process_name: "ordsys"
wsgi_module: ordsys.wsgi

website:
  - fqdn: "{{ fqdn }}"
    template: "ordsys"
    static_root: "{{ static_root }}"
    media_root: "{{ media_root }}"
    process_name: "{{ process_name }}"

environment_variables:
  SECRET_KEY: "{{ django_secret_key }}"
  DB_PASSWORD: "{{ db_password }}"
  SENTRY_DSN: "{{ vault_ordsys_sentry_dsn }}"
  DJANGO_SETTINGS_MODULE: "{{ django_settings }}"
