---
user: ordsys
process_group: www-data
fqdn_frontend: "ordsys.utn.se"
fqdn_backend: "ordsysbackend.utn.se"
install_root: /var/www
project_name: ordsys
project_folder: "{{ install_root }}/{{ project_name }}"

project_repo: "git@github.com:chwallen/ordsys.git"
node_version: "14.8.0"

db_name: ordsys
db_user: ordsys
db_password: "{{ vault_ordsys_db_password }}"

django_secret_key: "{{ vault_ordsys_secret_key }}"
django_settings: ordsys.settings.production
pythonpath: "{{ project_folder }}"

static_root: "{{ pythonpath }}/ordsys/static/"
media_root: "{{ pythonpath }}/ordsys/media/"

process_name: "ordsys"
asgi_module: ordsys.asgi:application

website:
  - fqdn: "{{ fqdn }}"
    template: "ordsys"
    static_root: "{{ static_root }}"
    media_root: "{{ media_root }}"
    process_name: "{{ process_name }}"

environment_variables:
  SECRET_KEY: "{{ django_secret_key }}"
  DB_PASSWORD: "{{ db_password }}"
  SENTRY_DSN: "{{ vault_ordsys_sentry_dsn }}"
  DJANGO_SETTINGS_MODULE: "{{ django_settings }}"
