---
user: ordsys
process_group: www-data
fqdn: "ordsys.utn.se"
install_root: /var/www
project_name: ordsys
project_folder: "{{ install_root }}/{{ project_name }}"
git_repo: "git@github.com:chwallen/ordsys.git"
node_version: "14.8.0"
db_name: ordsys
db_user: ordsys
db_password: "{{ vault_ordsys_db_password }}"
django_secret_key: "{{ vault_ordsys_secret_key }}"
django_settings: ordsys.settings.production
