---
- name: Install admininterface
  hosts: django
  vars_files:
    - vars/passwords.yml
    - vars/django/admininterface.yml
  become: yes
  become_flags: -HE # Keep the ssh-agent when using sudo so that private github repo can be pulled. Requires that you have your ssh key added in an ssh-agent
  roles:
    - role: django
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: "admininterface-privatekey.json"
