---
- name: Manage Users
  hosts: all
  become: yes
  vars_files:
    - vars/users.yml
  roles:
    - logins

- name: Enable Firewall
  hosts: all
  become: yes
  tasks:
    - name: Allow SSH connections
      ufw: rule=allow port=ssh

    - name: Enable Firewall
      ufw: state=enabled policy=deny
