# Custom installations on babbage

- name: Deploy custom installations
  hosts: drupal7
  become: yes
  vars_files:
    - vars/custom_installations_babbage.yml
  roles:
    - role: logs
      websites: "{{ custom_installations }}"
      tags: logs
    - role: nginx
      websites: "{{ custom_installations }}"
      tags: nginx
  tasks:
    - name: Install dependencies for custom installations
      apt:
        name: composer
        state: present

    - name: Ensures public dirs exists
      file: path={{ item.web_root }}/public state=directory recurse=true owner={{item.user}} group=www-data
      with_items: "{{ custom_installations }}"

    - name: Change permission on wp-content (Wordpress only)
      file:
        path: "{{item.web_root}}/public/wp-content"
        state: directory
        owner: "{{ item.user }}"
        group: www-data
        recurse: true
        mode: "u=rwX,g=rwX,o=rX"
      with_items: "{{ custom_installations }}"
      when: item.template == 'wordpress'

- name: create databases
  hosts: drupal7
  become: yes
  vars_files:
    - vars/passwords.yml
    - vars/custom_installations_babbage.yml
  roles:
    - role: mysql
      databases: "{{ custom_databases }}"
  tags: database
