# TODO: Combine with Drupal7 role?
---
- name: Deploy custom installations
  hosts: application
  become: yes
  vars_files:
    - vars/custom_installations.yml
  roles:
    - role: nginx
      websites: "{{ custom_installations }}"
  tasks:
    - name: Ensures public dirs exists
      file: path={{ item.web_root }}/public state=directory recurse=true owner={{item.user}} group=www-data
      with_items: "{{ custom_installations }}"
