# Hugo is installed via snap since it provides the latest version of hugo.
# There is a version of hugo availabe via apt however it is poorly
# maintained and lie many versions behind (as of 17/3 2020).

# Since snap only give access to home directories for the snap, a user
# called hugo has to be used where the website files are generated.
# The reason for having a seperate user is that it will outlive the
# users created for the system administrators.

---
- name: Deploy Documentation website
  hosts: application
  vars:
    url: "docs.utn.se"
    repo: "https://github.com/UTNkar/documentation.git"
    web_root: "/home/hugo/docs.utn.se"
  become: yes
  pre_tasks:
    - name: Create user for hugo
      user:
        name: hugo
        shell: "/bin/bash"
     
    - name: Get git repository
      git: 
        repo: "{{ repo }}" 
        dest: "{{ web_root }}" 
        accept_hostkey: yes
      become_user: hugo

    - name: Install Hugo
      snap:
        name: hugo

    - name: Hugo Generate
      shell: hugo
      args:
        chdir: "{{ web_root }}"
      become_user: hugo

    - name: Fix permissions
      file: 
        path: "{{ web_root }}"
        owner: hugo
        group: www-data
        recurse: yes
  roles:
    - role: nginx
      websites:
        - fqdn: "{{ url }}"
          web_root: "{{ vars.web_root }}"
          template: "html-ssl"
