- name: Create Drupal 7 Areas
  hosts: drupal7
  become: yes
  vars_files:
    - vars/passwords.yml
    - vars/drupal7_installations.yml
  roles:
    - role: drupal7_area
      areas: "{{ drupal7_installations }}"
