---
# Npm run build requires more memory than the moore server has so it has to be
# created locally on your computer. Requires that you have nvm installed on your computer
# in your home directory

- name: Create frontend build folder
  hosts: 127.0.0.1
  connection: local
  tags: frontend
  vars_files:
    - roles/ordsys/vars/main.yml
  tasks:
    - name: Clone/pull project repo
      git:
        repo: "{{ project_repo }}"
        dest: "/tmp/ordsys"
        accept_hostkey: yes
        version: master

    - name: Install node
      shell: >
        . ~/.nvm/nvm.sh && nvm install {{ node_version }}
      args:
        chdir: "/tmp/ordsys/frontend"

    - name: Install dependencies
      shell: >
        . ~/.nvm/nvm.sh && nvm exec {{ node_version }} npm install --production
      args:
        chdir: "/tmp/ordsys/frontend"
      ignore_errors: yes

    - name: Create production build (takes long time)
      shell: >
        . ~/.nvm/nvm.sh && nvm exec {{ node_version }} npm run build
      args:
        chdir: "/tmp/ordsys/frontend"

- name: Move frontend build to server
  hosts: django
  gather_facts: yes
  vars_files:
    - roles/ordsys/vars/main.yml
  tags: sync
  tasks:
  - name: Copy build folder to user directory (because of permissions)
    synchronize:
      src: /tmp/ordsys/frontend/build/
      dest: ~/build

  # Using the syncronize module doesn't work since it executes the command
  # from your local computer which means that it can't get root access which it needs
  - name: Copy build folder to correct location on server
    become: yes
    become_flags: -HE
    shell: >
      rsync -a /home/{{ ansible_user_id }}/build/ /var/www/ordsys/frontend/build

  - name: Fix permissions on build folder
    become: yes
    become_flags: -HE
    file:
      path: "{{ project_folder }}/frontend/build"
      state: directory
      recurse: yes
      owner: "{{ user }}"
      group: "{{ process_group }}"

  - name: Remove temporary build folder on server
    file:
      path: ~/build
      state: absent

  - name: Remove temporary build folder on local computer
    file:
      path: /tmp/ordsys
      state: absent
    delegate_to: "localhost"


- name: Install ordsys
  hosts: django
  become: yes
  become_flags: -HE
  vars_files:
    - vars/passwords.yml
  roles:
    - role: ordsys
