---
- hosts: all
  become: true
  tasks:
    - name: upgrade all packages
      apt: update_cache=yes upgrade=dist
    - name: check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: reboot if required
      reboot:
      when: reboot_required_file.stat.exists
