---
- hosts: all
  become: true
  tasks:
   - name: update apt cache
     apt: update_cache=yes
   - name: upgrade all packages
     apt: upgrade=dist
   - name: reboot if required
     command: /sbin/reboot
     args:
       removes: /var/run/reboot-required
