---
- hosts: all
  become: true
  tasks:
   - name: upgrade all packages
     apt: update_cache=yes upgrade=dist
   - name: reboot if required
     command: /sbin/reboot
     args:
       removes: /var/run/reboot-required
