# any directories that need to be added to the PYTHONPATH.
virtualenv: "{{ install_root }}/{{ project_name }}/venv"

static_root: "{{ pythonpath }}/static/"
media_root: "{{ pythonpath }}/media/"

# apt packages
system_packages:
  - git
  - postgresql
  - python3
  - python3-pip
  - python3-venv
  - python3-dev
  - build-essential
  - libpq-dev
  - redis-server
