- name: Download nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  become: yes
  become_user: "{{ user }}"

- name: Install node
  shell: nvm install {{ node_version }}
  become: yes
  become_user: "{{ user }}"

- name: Install dependencies
  npm:
    path: "{{ web_root }}"
    production: yes
  notify:
    - perform reload
  become: yes
  become_user: "{{ user }}"

- name: Create production build
  shell: npm run build
  become: yes
  become_user: "{{ user }}"

- name: Install serve
  npm:
    name: serve
    path: "{{ web_root }}"

- name: copy ordsys service config
  template:
    src: templates/service.j2
    dest: "/etc/systemd/system/{{process_name}}.service"
    mode: "600"

- name: restart ordsys service
  systemd:
    name: "{{process_name}}.service"
    state: restarted
    daemon_reload: yes
