---
- name: Setup backend
  include_role:
    name: django
  vars:
    virtualenv: "{{ project_folder }}/venv"
    process_user: "{{ user }}"
    run_nginx: no
    use_daphne: yes
    use_gunicorn: no
  tags: backend

- name: Fix permissions
  file:
    path: "{{ project_folder }}"
    owner: "{{ user }}"
    group: www-data
    state: directory
    recurse: true
    mode: "u=rwX,g=rX,o=rX"

- name: Setup nginx
  include_role:
    name: nginx
  vars:
    websites:
      - fqdn: "{{ fqdn_backend }}"
        web_root: "{{ project_folder }}"
        user: "{{ user }}"
        template: "ordsys-backend"
      - fqdn: "{{ fqdn_frontend }}"
        web_root: "{{ project_folder }}"
        user: "{{ user }}"
        template: "ordsys-frontend"
