---
- name: Setup backend
  include_role:
    name: django
  vars:
    virtualenv: "{{ project_folder }}/venv"
    process_user: "{{ user }}"
    run_nginx: no
    use_daphne: yes
  tags: backend

- name: Run frontend tasks
  include: frontend.yml
  tags: frontend

- name: Fix permissions
  file:
    path: "{{ project_folder }}"
    owner: "{{ user }}"
    group: www-data
    state: directory
    recurse: true
    mode: "u=rwX,g=rX,o=rX"

- name: Setup nginx
  include_role:
    name: nginx
  vars:
    websites:
      - fqdn: "{{ fqdn }}"
        web_root: "{{ project_folder }}"
        user: "{{ user }}"
        template: "ordsys"
