---
- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql
    # For PostgreSQL ansible support
    - python-psycopg2
    - php-fpm
    - php-mbstring
    - php-pgsql
    - php-gd

- become: yes
  become_user: postgres
  include: create_db.yml

- name: Download Limesurvey package
  get_url:
    url: "{{ url }}"
    dest: "/tmp/{{ package }}"

- name: Ensures web_root dir exists
  file:
    path: "{{ web_root }}"
    state: directory
    group: www-data

- name: Extract Limesurvey package
  unarchive:
    copy: no
    src: "/tmp/{{ package }}"
    dest: "{{ web_root }}"
    owner: root
    group: www-data
    creates: "{{ web_root }}/limesurvey"

- name: Fix permissions
  file:
    path: "{{ web_root }}/{{ item }}"
    owner: www-data
    recurse: yes
  with_items:
    - limesurvey/tmp
    - limesurvey/upload
    - limesurvey/application/config

- name: Setup nginx
  import_role:
    name: nginx
  tags: nginx
  vars:
    websites:
      - fqdn: "{{ fqdn }}"
        template: "limesurvey"
        web_root: "{{ web_root }}"
