- name: fix permissions
  file:
    path: "{{ install_root }}/{{ project_name }}"
    state: directory
    owner: "{{ process_user }}"
    group: "{{ process_group }}"
    recurse: yes

- name: fix permission on private key
  file:
    path: "{{ install_root }}/{{ project_name }}/adminInterface/admininterface-privatekey.json"
    mode: '0640'
  when: project_name == 'admininterface'

- name: restart socket
  systemd:
    name: "{{process_name}}.socket"
    state: stopped
    daemon_reload: yes
  when: use_socket

- name: restart service
  systemd:
    name: "{{process_name}}.service"
    state: restarted
    daemon_reload: yes
