---
- name: Install dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - nginx
    - hugo

- name: Get Documentation from Git
  git: repo={{documentation.repo}} dest={{documentation.web_root}} accept_hostkey=yes

- name: Hugo Generate
  shell: hugo
  args:
    chdir: "{{documentation.web_root}}"

- name: Fix permissions
  file: path={{ documentation.web_root }} group=www-data recurse=yes

- name: Add NGINX configuration
  template: src=nginx.j2 dest=/etc/nginx/sites-available/{{ documentation.fqdn }}
  notify:
    - reload nginx

- name: Enable NGINX configuration
  file: path=/etc/nginx/sites-enabled/{{ documentation.fqdn }} src=/etc/nginx/sites-available/{{ documentation.fqdn }} state=link
  notify:
    - reload nginx
