- name: Copy firebase private key
  copy:
    src: "files/admininterface-privatekey.json"
    dest: "{{ install_root }}/{{ project_name }}/adminInterface/admininterface-privatekey.json"
    owner: "{{ process_user }}"
    group: "{{ process_group }}"
    mode: "0640"
  when: project_name == 'admininterface'
  notify:
    - restart socket
    - restart service
    - fix permissions
    - fix permission on private key

- name: Update pip
  pip:
    name: pip
    state: latest
    virtualenv: "{{ virtualenv }}"
    virtualenv_command: "pyvenv"

- name: install python packages
  pip:
    requirements: "{{ install_root }}/{{ project_name }}/requirements.txt"
    virtualenv: "{{ virtualenv }}"
    virtualenv_command: "pyvenv"
  notify:
    - restart socket
    - restart service
    - fix permissions
    - fix permission on private key
  become_user: "{{process_user}}"

- name: django migrate
  become_user: "{{process_user}}"
  environment:
    DJANGO_SECRET: "{{ django_secret_key }}"
    DJANGO_DB_PASS: "{{ db_password }}"
  django_manage:
    command: migrate
    app_path: "{{ pythonpath }}"
    virtualenv: "{{ virtualenv }}"
    settings: "{{ django_settings }}"

- name: fix permissions
  file:
    path: "{{ install_root }}/{{ project_name }}"
    state: directory
    owner: "{{ process_user }}"
    group: "{{ process_group }}"
    recurse: yes

- name: django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ pythonpath }}"
    virtualenv: "{{ virtualenv }}"
    settings: "{{ django_settings }}"
  notify:
    - fix permissions
  become_user: "{{process_user}}"

- name: django cron
  django_manage:
    command: installtasks
    app_path: "{{ pythonpath }}"
    virtualenv: "{{ virtualenv }}"
    settings: "{{ django_settings }}"
  become_user: "{{process_user}}"
  environment:
    SENTRY_DSN: "{{ environment_variables.SENTRY_DSN }}"

- name: Setup gunicorn
  include_role:
    name: gunicorn
