- name: install gunicorn
  pip:
    name: gunicorn
    virtualenv: "{{ virtualenv }}"
    virtualenv_command: "pyvenv"
  become_user: "{{ process_user }}"

- name: copy gunicorn service config
  template:
    src: templates/gunicorn.service.j2
    dest: "/etc/systemd/system/{{process_name}}.service"
    mode: "600"
  vars:
    working_dir: "{{ pythonpath }}"
  notify:
    - restart socket
    - restart service

- name: copy gunicorn socket config
  template:
    src: templates/gunicorn.socket.j2
    dest: "/etc/systemd/system/{{process_name}}.socket"
    mode: "600"
  notify:
    - restart socket
    - restart service

- name: copy gunicorn tmpfiles config
  template:
    src: templates/tmpfiles.gunicorn.conf.j2
    dest: "/etc/tmpfiles.d/{{process_name}}.conf"
  notify:
    - restart socket
    - restart service

- name: make sure gunicorn server is running
  service:
    name: "{{process_name}}"
    state: started
    enabled: yes
