- name: install gunicorn
  pip:
    name: gunicorn
    virtualenv: "{{ virtualenv }}"
    virtualenv_command: "pyvenv"
  become_user: "{{ process_user }}"

- name: copy gunicorn service config
  template:
    src: templates/gunicorn.service.j2
    dest: "/etc/systemd/system/{{process_name}}.service"
    mode: "600"
  vars:
    working_dir: "{{ pythonpath }}"
  notify:
    - restart socket
    - restart service
