---
- name: Include setup tasks
  include: setup.yml
  tags: setup

- name: Include deploy tasks
  include: deploy.yml
  tags: deploy

- name: Include nginx tasks
  tags: nginx
  import_role:
    name: nginx
  vars:
    websites:
      - fqdn: "{{ server_name }}"
        file: "moore.utn.se"
        certfile: "moore.utn.se"
        template: "django-https"
        static_root: "{{ static_root }}"
        media_root: "{{ media_root }}"
        process_name: "{{ process_name }}"