---
- name: Include setup tasks
  include: setup.yml
  tags: setup

- name: Include postgres tasks
  include: postgres.yml
  tags: postgres

- name: Include deploy tasks
  include: deploy.yml
  tags: deploy

- name: Include nginx tasks
  tags: nginx
  import_role:
    name: nginx
  vars:
    websites: "{{ website }}"
