---
- name: Include setup tasks
  include: setup.yml
  tags: setup

- name: Include deploy tasks
  include: deploy.yml
  tags: deploy

- name: Include gunicorn tasks
  include: gunicorn.yml
  when: use_gunicorn

- name: Include daphne tasks
  include: daphne.yml
  when: use_daphne

- name: Include nginx tasks
  tags: nginx
  import_role:
    name: nginx
  vars:
    websites: "{{ website }}"
  when: run_nginx
