---
- name: install system packages
  apt:
    pkg: "{{ system_packages }}"
    update-cache: yes

- name: create system user
  user:
    name: "{{ process_user }}"
    shell: /usr/sbin/nologin
    system: yes

- name: create site folder
  file:
    path: "{{ install_root }}/{{ project_name }}"
    state: directory
    mode: '0755'
    owner: '{{ process_user }}'
    group: '{{ process_group }}'
