---
- name: Install dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - php-fpm
    - php-mbstring
    - php-mysql
    - php-gd
    - php-xml
    - php-json

- include: permissions.yml
