---
- name: Install dependencies
  apt: 
    name:
      - php-fpm
      - php-mbstring
      - php-mysql
      - php-gd
      - php-xml
      - php-json
    state: present

- include: permissions.yml
