---
- name: Install dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - php-fpm
    - php-mbstring
    - php-mysql
    - php-gd
    - php-xml
    - php-json

- name: Ensures web_root dirs exists
  file: path={{ item.web_root }} state=directory group=www-data
  with_items: "{{ areas }}"

- name: Ensures public dirs exists
  file: path={{ item.web_root }}/public state=directory group=www-data
  with_items: "{{ areas }}"
