---
- name: Add Users
  user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.groups }}"
    shell: "{{ item.shell }}"
    home: "{{ item.home }}"
    append: no
  with_items: "{{ users }}"
  when: '"{{ inventory_hostname }}" in "{{ item.hosts }}"'

- name: Home Directory
  file:
    path: "{{ item.home }}"
    state: directory
    owner: "{{ item.name }}"
  with_items: "{{ users }}"
  when: '"{{ inventory_hostname }}" in "{{ item.hosts }}"'

- name: Add Public Keys
  authorized_key: user={{ item.name }} key="{{ item.ssh_pubkey }}" state=present exclusive=yes
  with_items: "{{ users }}"
  when: '"{{ inventory_hostname }}" in "{{ item.hosts }}"'
