---
- name: Add Users
  user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.groups }}"
    shell: "{{ item.shell }}"
    home: "{{ item.home }}"
    # password: changeme
    password: $6$rounds=656000$BjZCF3F110zBo2mU$NoK.h2vYyeX6O8eXhsj.C3NkTkfOqnaI7HC.x20h7pKodTMQ9JKUS8wA2bpFx.JOqw7QSBviPZrzu0uniyWOF1
    update_password: on_create
    append: no
  with_items: "{{ users }}"
  when: inventory_hostname in item.hosts

- name: Home Directory
  file:
    path: "{{ item.home }}"
    state: directory
    owner: "{{ item.name }}"
  with_items: "{{ users }}"
  when: inventory_hostname in item.hosts

- name: Add Public Keys
  authorized_key: 
    user: "{{ item.name }}"
    key: "{{ item.ssh_pubkey }}" 
    state: present
    exclusive: yes
  with_items: "{{ users }}"
  when: inventory_hostname in item.hosts
