---
- include: add_users.yaml
- include: delete_users.yaml

- name: disable PasswordAuthentication
  lineinfile: dest=/etc/ssh/sshd_config regexp='^#?PasswordAuthentication (yes|no)$' line='PasswordAuthentication no' state=present
  notify:
  - restart sshd

- name: Disallow SSH password authentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^PasswordAuthentication"
    line="PasswordAuthentication no"
    state=present
  notify:
    - restart sshd
